[package]
name = "lost-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
wgpu = "0.19"
winit = { version = "0.29", features = ["rwh_05"] }
pollster = "0.3"